/**
 * POKE RISC-V Assembler Tests
 *
 * Tests asm_rv.js (RV32IM instruction encoding).
 * Each test verifies the generated bytes match expected RISC-V machine code.
 */

const { assembleRV } = require('../hub/assembler/asm_rv')

let passed = 0, failed = 0, total = 0

function test(name, fn) {
  total++
  try {
    fn()
    passed++
    console.log(`  PASS  ${name}`)
  } catch (e) {
    failed++
    console.log(`  FAIL  ${name}: ${e.message}`)
  }
}

function eq(a, b, msg) {
  if (a !== b) throw new Error(`${msg || ''} expected ${b}, got ${a}`)
}

function hex(buf) { return buf.toString('hex') }

// Helper: assemble and return hex string
function asm(code) { return hex(assembleRV(code)) }
function asmLen(code) { return assembleRV(code).length }

console.log('\n  RISC-V Assembler Tests\n')

// ── Pseudo-instructions ──
test('nop → addi x0, x0, 0', () => eq(asm('nop'), '13000000'))
test('ret → jalr x0, x1, 0', () => eq(asm('ret'), '67800000'))
test('nop + ret', () => eq(asmLen('nop\nret'), 8))

// ── LI (load immediate) ──
test('li a0, 0', () => eq(asmLen('li a0, 0'), 4))  // addi a0, x0, 0
test('li a0, 42', () => { const b = assembleRV('li a0, 42'); eq(b.length, 4); eq(b[0] & 0x7F, 0x13) })  // I-type
test('li a0, -1', () => eq(asmLen('li a0, -1'), 4))
test('li a0, 0x12345', () => { const b = assembleRV('li a0, 0x12345'); eq(b.length >= 4, true) })  // needs lui+addi

// ── R-type ALU ──
test('add a0, a1, a2', () => { const b = assembleRV('add a0, a1, a2'); eq(b.length, 4) })
test('sub a0, a1, a2', () => { const b = assembleRV('sub a0, a1, a2'); eq(b.length, 4) })
test('and a0, a1, a2', () => eq(asmLen('and a0, a1, a2'), 4))
test('or a0, a1, a2', () => eq(asmLen('or a0, a1, a2'), 4))
test('xor a0, a1, a2', () => eq(asmLen('xor a0, a1, a2'), 4))
test('sll a0, a1, a2', () => eq(asmLen('sll a0, a1, a2'), 4))
test('srl a0, a1, a2', () => eq(asmLen('srl a0, a1, a2'), 4))
test('sra a0, a1, a2', () => eq(asmLen('sra a0, a1, a2'), 4))
test('slt a0, a1, a2', () => eq(asmLen('slt a0, a1, a2'), 4))
test('mul a0, a1, a2', () => eq(asmLen('mul a0, a1, a2'), 4))
test('div a0, a1, a2', () => eq(asmLen('div a0, a1, a2'), 4))
test('rem a0, a1, a2', () => eq(asmLen('rem a0, a1, a2'), 4))

// ── I-type ALU ──
test('addi a0, a1, 10', () => eq(asmLen('addi a0, a1, 10'), 4))
test('andi a0, a1, 0xFF', () => eq(asmLen('andi a0, a1, 0xFF'), 4))
test('ori a0, a1, 0x3', () => eq(asmLen('ori a0, a1, 0x3'), 4))
test('xori a0, a1, 1', () => eq(asmLen('xori a0, a1, 1'), 4))
test('slti a0, a1, 5', () => eq(asmLen('slti a0, a1, 5'), 4))
test('slli a0, a1, 4', () => eq(asmLen('slli a0, a1, 4'), 4))
test('srli a0, a1, 4', () => eq(asmLen('srli a0, a1, 4'), 4))
test('srai a0, a1, 4', () => eq(asmLen('srai a0, a1, 4'), 4))

// ── Load/Store ──
test('lw a0, 0(a1)', () => eq(asmLen('lw a0, 0(a1)'), 4))
test('lw a0, 16(sp)', () => eq(asmLen('lw a0, 16(sp)'), 4))
test('sw a0, 0(a1)', () => eq(asmLen('sw a0, 0(a1)'), 4))
test('lb a0, 0(a1)', () => eq(asmLen('lb a0, 0(a1)'), 4))
test('sb a0, 0(a1)', () => eq(asmLen('sb a0, 0(a1)'), 4))
test('lh a0, 0(a1)', () => eq(asmLen('lh a0, 0(a1)'), 4))
test('lbu a0, 0(a1)', () => eq(asmLen('lbu a0, 0(a1)'), 4))

// ── Branch (forward) ──
test('beq forward label', () => {
  const b = assembleRV('beq a0, a1, done\nnop\ndone:\nret')
  eq(b.length, 12)  // branch + nop + ret
})
test('bne forward label', () => {
  const b = assembleRV('bne a0, zero, skip\nnop\nskip:\nret')
  eq(b.length, 12)
})
test('blt forward', () => eq(asmLen('blt a0, a1, end\nend:\nret'), 8))
test('bge forward', () => eq(asmLen('bge a0, a1, end\nend:\nret'), 8))

// ── Branch (backward — loop) ──
test('backward branch (loop)', () => {
  const b = assembleRV('li a0, 0\nli a1, 10\nloop:\naddi a0, a0, 1\nbne a0, a1, loop\nret')
  eq(b.length, 20)
})

// ── JAL / JALR ──
test('jal label', () => eq(asmLen('jal func\nnop\nfunc:\nret'), 12))
test('jal ra, label', () => eq(asmLen('jal ra, func\nnop\nfunc:\nret'), 12))
test('j label', () => eq(asmLen('j end\nnop\nend:\nret'), 12))
test('jalr ra', () => eq(asmLen('jalr ra'), 4))
test('jalr x0, ra, 0', () => eq(asmLen('jalr x0, ra, 0'), 4))

// ── Upper immediate ──
test('lui a0, 0x12345', () => eq(asmLen('lui a0, 0x12345'), 4))
test('auipc a0, 0x1000', () => eq(asmLen('auipc a0, 0x1000'), 4))

// ── MV pseudo ──
test('mv a0, a1', () => eq(asmLen('mv a0, a1'), 4))

// ── System ──
test('ecall', () => eq(asm('ecall'), '73000000'))
test('ebreak', () => eq(asm('ebreak'), '73001000'))
test('fence.i', () => eq(asm('fence.i'), '0f100000'))

// ── Register names ──
test('x0-x31 registers', () => eq(asmLen('add x10, x11, x12'), 4))
test('named registers (a0, s0, t0, sp, ra)', () => {
  eq(asmLen('add a0, s0, t0'), 4)
  eq(asmLen('addi sp, sp, -16'), 4)
  eq(asmLen('mv a0, ra'), 4)
})

// ── Comments ──
test('# comments stripped', () => eq(asmLen('nop # comment\nret'), 8))
test('// comments stripped', () => eq(asmLen('nop // comment\nret'), 8))

// ── Multi-line programs ──
test('fibonacci (a0=10th fib)', () => {
  const b = assembleRV(`
    li a0, 0
    li a1, 1
    li a2, 10
    loop:
      add a3, a0, a1
      mv a0, a1
      mv a1, a3
      addi a2, a2, -1
      bne a2, zero, loop
    ret
  `)
  eq(b.length > 0, true)
  eq(b.length % 4, 0, 'must be 4-byte aligned')
})

test('sum 1 to N', () => {
  const b = assembleRV(`
    li a0, 0
    li a1, 1
    li a2, 100
    loop:
      add a0, a0, a1
      addi a1, a1, 1
      bge a1, a2, done
      j loop
    done:
      ret
  `)
  eq(b.length > 0, true)
})

// ── Error handling ──
test('unknown instruction throws', () => {
  let threw = false
  try { assembleRV('invalid_op a0, a1') } catch(e) { threw = true }
  eq(threw, true, 'should throw on unknown instruction')
})

test('undefined label throws', () => {
  let threw = false
  try { assembleRV('j nowhere') } catch(e) { threw = true }
  eq(threw, true, 'should throw on undefined label')
})

console.log(`\n  ${passed} passed, ${failed} failed, ${total} total\n`)
process.exit(failed > 0 ? 1 : 0)
