FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y qemu-system-x86 --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /poke

# Pre-built kernel image (built locally with cross-compiler)
COPY poke.img ./

EXPOSE 8080

CMD ["qemu-system-i386", \
     "-drive", "format=raw,file=/poke/poke.img", \
     "-m", "64M", \
     "-vga", "std", \
     "-device", "e1000,netdev=net0", \
     "-netdev", "user,id=net0,hostfwd=tcp::8080-:80", \
     "-device", "virtio-rng-pci", \
     "-device", "virtio-balloon-pci", \
     "-display", "none", \
     "-monitor", "none", \
     "-nographic"]
