FROM node:20-slim

RUN apt-get update && apt-get install -y nasm curl --no-install-recommends \
    && curl -fsSL https://get.docker.com | sh \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /poke

COPY package.json ./
RUN npm install --production

COPY src/ ./src/
COPY hub/ ./hub/
COPY web/ ./web/
COPY profiles/ ./profiles/

EXPOSE 3333

CMD ["node", "src/hub.js"]
